import {
  Folder, Newspaper, Award, GraduationCap, Brain, Sparkles, Megaphone, BookOpen, Microscope,
  Calendar, Briefcase, Globe, Users, Rocket, Lightbulb, Zap, Star, TrendingUp, Medal,
  Building, Camera, Code, Coffee, FlaskConical, Heart, Laptop, Map, Music,
  Palette, Shield, Target, Tent, Trophy, Video
} from "lucide-react";

export const PREDEFINED_ICONS = [
  { name: "folder", icon: Folder, label: "Папка" },
  { name: "newspaper", icon: Newspaper, label: "Новини" },
  { name: "award", icon: Award, label: "Нагорода" },
  { name: "graduation-cap", icon: GraduationCap, label: "Освіта" },
  { name: "brain", icon: Brain, label: "Інтелект" },
  { name: "sparkles", icon: Sparkles, label: "Інновації" },
  { name: "megaphone", icon: Megaphone, label: "Оголошення" },
  { name: "book-open", icon: BookOpen, label: "Книга" },
  { name: "microscope", icon: Microscope, label: "Наука" },
  { name: "calendar", icon: Calendar, label: "Події" },
  { name: "briefcase", icon: Briefcase, label: "Бізнес" },
  { name: "globe", icon: Globe, label: "Світ" },
  { name: "users", icon: Users, label: "Люди" },
  { name: "rocket", icon: Rocket, label: "Запуск" },
  { name: "lightbulb", icon: Lightbulb, label: "Ідея" },
  { name: "zap", icon: Zap, label: "Швидкість" },
  { name: "star", icon: Star, label: "Зірка" },
  { name: "trending-up", icon: TrendingUp, label: "Тренд" },
  { name: "medal", icon: Medal, label: "Медаль" },
  { name: "building", icon: Building, label: "Інститут" },
  { name: "camera", icon: Camera, label: "Фото" },
  { name: "code", icon: Code, label: "Код" },
  { name: "coffee", icon: Coffee, label: "Кава" },
  { name: "flask-conical", icon: FlaskConical, label: "Досліди" },
  { name: "heart", icon: Heart, label: "Здоров'я" },
  { name: "laptop", icon: Laptop, label: "IT" },
  { name: "map", icon: Map, label: "Мапа" },
  { name: "music", icon: Music, label: "Музика" },
  { name: "palette", icon: Palette, label: "Дизайн" },
  { name: "shield", icon: Shield, label: "Безпека" },
  { name: "target", icon: Target, label: "Ціль" },
  { name: "tent", icon: Tent, label: "Кемпінг" },
  { name: "trophy", icon: Trophy, label: "Кубок" },
  { name: "video", icon: Video, label: "Відео" },
];
