// Package qdrant implements domain.VectorStore using the Qdrant vector database.
// It manages a single collection ("university_docs") with 1024-dimensional
// cosine similarity vectors generated by the BAAI/bge-m3 embedding model.
package qdrant

import (
	"context"
	"fmt"

	"github.com/qdrant/go-client/qdrant"
	"university-chatbot/backend/internal/domain"
)

const (
	collectionName = "university_docs"
	vectorSize = 1024
	topKDense  = 5
	topKSparse = 3
)
// Client wraps a Qdrant gRPC connection and an embedder (domain.LLMClient.Embed).
// It implements domain.VectorStore.
type Client struct {
	conn       *qdrant.Client
	embedder   interface {
		Embed(ctx context.Context, text string) ([]float32, error)
	}
}

// NewClient creates a Qdrant gRPC client. If apiKey is non-empty, TLS is enabled.
func NewClient(ctx context.Context, url, apiKey string, embedder interface {
	Embed(ctx context.Context, text string) ([]float32, error)
}) (*Client, error) {
	cfg := &qdrant.Config{
		Host: url,
		Port: 6334,
	}
	if apiKey != "" {
		cfg.APIKey = apiKey
		cfg.UseTLS = true
	}

	conn, err := qdrant.NewClient(cfg)
	if err != nil {
		return nil, fmt.Errorf("qdrant: connect: %w", err)
	}
	return &Client{conn: conn, embedder: embedder}, nil
}

// EnsureCollection creates the "university_docs" collection if it doesn't exist.
// Uses cosine distance with 1024-dimensional vectors.
func (c *Client) EnsureCollection(ctx context.Context) error {
	exists, err := c.conn.CollectionExists(ctx, collectionName)
	if err != nil {
		return fmt.Errorf("qdrant: check collection: %w", err)
	}
	if exists {
		return nil
	}

	err = c.conn.CreateCollection(ctx, &qdrant.CreateCollection{
		CollectionName: collectionName,
		VectorsConfig: qdrant.NewVectorsConfig(&qdrant.VectorParams{
			Size:     vectorSize,
			Distance: qdrant.Distance_Cosine,
		}),
	})
	if err != nil {
		return fmt.Errorf("qdrant: create collection: %w", err)
	}
	return nil
}

func (c *Client) Ping(ctx context.Context) error {
	_, err := c.conn.HealthCheck(ctx)
	return err
}

// UpsertChunks embeds each chunk's text and upserts the resulting point
// (vector + payload) into Qdrant. Payload includes document_id, document_name,
// text, page_number, and any chunk metadata.
func (c *Client) UpsertChunks(ctx context.Context, chunks []domain.Chunk) error {
	points := make([]*qdrant.PointStruct, 0, len(chunks))

	for _, chunk := range chunks {
		vec, err := c.embedder.Embed(ctx, chunk.Text)
		if err != nil {
			return fmt.Errorf("qdrant: embed chunk %s: %w", chunk.ID, err)
		}

		payload := map[string]*qdrant.Value{
			"document_id":   qdrant.NewValueString(chunk.DocumentID),
			"document_name": qdrant.NewValueString(chunk.DocumentName),
			"text":          qdrant.NewValueString(chunk.Text),
			"page_number":   qdrant.NewValueInt(int64(chunk.PageNumber)),
		}
		for k, v := range chunk.Metadata {
			payload[k] = qdrant.NewValueString(v)
		}

		points = append(points, &qdrant.PointStruct{
			Id:      qdrant.NewIDUUID(chunk.ID),
			Vectors: qdrant.NewVectorsDense(vec),
			Payload: payload,
		})
	}

	_, err := c.conn.Upsert(ctx, &qdrant.UpsertPoints{
		CollectionName: collectionName,
		Points:         points,
	})
	return err
}

// HybridSearch embeds the query text and performs a dense vector search,
// returning up to topK results with their similarity scores and payloads.
func (c *Client) HybridSearch(ctx context.Context, query string, topK int) ([]domain.SearchResult, error) {
	vec, err := c.embedder.Embed(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("qdrant: embed query: %w", err)
	}

	results, err := c.conn.Query(ctx, &qdrant.QueryPoints{
		CollectionName: collectionName,
		Query:          qdrant.NewQuery(vec...),
		Limit:          qdrant.PtrOf(uint64(topK)),
		WithPayload:    qdrant.NewWithPayload(true),
	})
	if err != nil {
		return nil, fmt.Errorf("qdrant: search: %w", err)
	}

	searchResults := make([]domain.SearchResult, 0, len(results))
	for _, r := range results {
		chunk := domain.Chunk{
			ID:           r.Id.GetUuid(),
			DocumentName: r.Payload["document_name"].GetStringValue(),
			DocumentID:   r.Payload["document_id"].GetStringValue(),
			Text:         r.Payload["text"].GetStringValue(),
			PageNumber:   int(r.Payload["page_number"].GetIntegerValue()),
		}
		searchResults = append(searchResults, domain.SearchResult{
			Chunk: chunk,
			Score: r.Score,
		})
	}
	return searchResults, nil
}

// DeleteByDocumentID removes all vector points whose document_id payload
// matches the given ID. Used when a document is deleted from the knowledge base.
func (c *Client) DeleteByDocumentID(ctx context.Context, documentID string) error {
	_, err := c.conn.Delete(ctx, &qdrant.DeletePoints{
		CollectionName: collectionName,
		Points: &qdrant.PointsSelector{
			PointsSelectorOneOf: &qdrant.PointsSelector_Filter{
				Filter: &qdrant.Filter{
					Must: []*qdrant.Condition{
						qdrant.NewMatchKeyword("document_id", documentID),
					},
				},
			},
		},
	})
	return err
}

// RenameDocumentPayload updates the document_name payload field for all
// points matching the given documentID. Used when an admin renames a document.
func (c *Client) RenameDocumentPayload(ctx context.Context, documentID string, newName string) error {
	_, err := c.conn.SetPayload(ctx, &qdrant.SetPayloadPoints{
		CollectionName: collectionName,
		Payload: map[string]*qdrant.Value{
			"document_name": qdrant.NewValueString(newName),
		},
		PointsSelector: &qdrant.PointsSelector{
			PointsSelectorOneOf: &qdrant.PointsSelector_Filter{
				Filter: &qdrant.Filter{
					Must: []*qdrant.Condition{
						qdrant.NewMatchKeyword("document_id", documentID),
					},
				},
			},
		},
	})
	return err
}
